---
- name: Task to install Apache2 on Ubuntu
  apt:
    name: apache2
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy custome page
  ansible.builtin.copy:
    src: /home/vagrant/ansible/WP-Pusher-Altschool-Exercise/WP PUSHER/
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Task to install Apache2 on CentOs
  yum:
    name: httpd
    state: present
  when: ansible_os_family == 'RedHat'

- name: Copy custome page
  ansible.builtin.copy:
    src: /home/vagrant/ansible/WP-Pusher-Altschool-Exercise/WP PUSHER/
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'RedHat'

- name: restart httpd
  service: 
    name: httpd
    state: restarted
  when: ansible_os_family == 'RedHat'