---

- name: start apache2 server
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'

- name: restart apache2
  service: 
    name: apache2
    state: restarted
  when: ansible_os_family == 'Debian'

- name: start httpd server
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: restart httpd
  service: 
    name: httpd
    state: restarted
  when: ansible_os_family == 'RedHat'